# Generated by Django 5.0.8 on 2024-08-10 13:15
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags_alter_comment_created'),
    ]

    operations = [
        TrigramExtension()
    ]
